. ./common.sh.security

sh alerts-host.sh "Hardware Tests MQTT" $GARDEN_HARDWARE_TESTS_MQTT_HOST $GARDEN_HARDWARE_TESTS_MQTT_SSH_USERNAME $GARDEN_HARDWARE_TESTS_MQTT_SSH_PASSWORD $GARDEN_HARDWARE_TESTS_MQTT_SSH_PORT